var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                          x                     ",
   "                                                         x!x                    ",
   "                                  xxxxxx                x!!!x                   ",
   "                                 x!!!!!!x              x!!!!!x                  ",
   "                                x!!!!!!!!x            x!!!!!!!x                 ",
   "                                x!!!!!!!!x        xxxxx   o    xxxxx            ",
   "                                x!!!!!!!!x        x                x            ",
   "                                 x!!!!!!x    xxx  x   yy  xx  o    x         xx ",
   "                                                  x                x         x  ",
   "                                     o            x                x         x  ",
   "                                                  x                x         x  ",
   "  xx                                             ox     yyy        x         x  ",
   "  x                                       p                        x         x  ",
   "  x            o       *  yyy             xx          xx       o   x         x  ",
   "  x        *    xx           o     yyyyyy        o       o         *         x  ",
   "  x                                                                          x  ",
   "  x       xxxx       yyyy      xxxx                 xxx  x     o    yyy      x  ",
   "  x                                    ***                                   x  ",
   "  x  @                                          xx                          kx  ",
   "  xxxxxxxxxx     xxxxx       xxxxxxxxxxxxxxxxxxx        x     xxxxxxxx   xxxxx  ",
   "           x!!!!!x                               x      x                       ",
   "           x!!!!!x                               x!!!!!!x                       ",
   "           xxxxxxx                               x!!!!!!x                       ",
   "                                                 x!!!!!!x                       ",
   "                                                 xxxxxxxx                       ",
   "                                                                                "],
  ["                                                                 xxxxxxx                          xxxxxxxxxxxx!x  ",
   "                                                               xxxx     xxxx                                 x!x  ",
   "                                      xxxxxxxxxxxxx          oxx           xx                                x!x  ",
   "                                      xx!!!!!!!!!!xx         xx             xx                               x!x  ",
   "                                       xxxxxxxxxx!!x         x                                    o   o   o  x!x  ",
   "                                                xx!x        xx     o   o                                  k xx!x  ",
   "                                                 x!x         x                                xxxxxxxxxxxxxxx!!x  ",
   "                                                 xvx         x     x   x                 !!!!!!!!!!!!!!!!!!!!!xx  ",
   "                                                             xx  |   |   |  xx           !xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xx!!!!!!!!!!!xx            v                        ",
   "          o                                                    xxxx!!!!!xx              x                         ",
   "         xxx                                           x            xxvxx                                         ",
   "                                                       x                                                          ",
   "                           o                           x                                                          ",
   "                          xxx                 x*       x                                                          ",
   "                                              xxx      x                                                          ",
   "                                              xo       x      o  o     x   x         xx                           ",
   "               x    xx        xxx             x        x               x   x         x                            ",
   "              xx     xx         x             x        x     xxxxxx    x   x   xxxxxxxxxx                         ",
   "             xx o     xx        x o           x      xxx               x   x   x               x                  ",
   "     @       x  x      x        x y           x        x               x   x   x               x                  ",
   "    xxx      x         x*       x             x        x               x   xxxxx   xxxx        x    x             ",
   "    x x      x         xx      xx o           x   *   x               x     o     x x         xx!!!!x             ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!!xx  y  xx!!!!!!!xxx    x               x     =     x x         x  x!!x              ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!xx       xxxxxxxxxx     x               xx   xxxxxxxx xx  o o  xx   xx               ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!x    o                 xx                              xx     xx                     ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!x    y                xx                                xxxxxxx                      ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!xx    p  xxxxxxxxxxxxxxx                                                             ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!!xyyyxxxxx!!!!!!!!!!!!x                                                              ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!x                                                               "],
  ["                                     v                                                                        ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                  |                                                 ",
   "                                                           !!!                                                ",
   "                                                           !x!                                                ",
   "                                                            x                                                 ",
   "                                                            x   oooo                                          ",
   "                                                            x   yyyy                                          ",
   "                                     ox                     xxxxxxxxxxxx                                      ",
   "                                     xx           x   x  p   x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x|x                               ",
   "                                      x   x           x                    x!!!x                              ",
   "                                      x   x           x                    oxvx                               ",
   "                                 x    x   xx          x              *                                        ",
   "                                      xx  x= = = =    x              x                                        ",
   "                                      x   x           x           x!!!x                                       ",
   "                                     *x  ox    = = = =x     o      xxx                                        ",
   "                                     xx   x           x     y                                                 ",
   "                              o   o       x           x     x                          oxxx                   ",
   "                                          x           x              x                 x!!!x                  ",
   "                             xxxpxxx xxxpxxx     o o  x!!!!!!!!!!!!!!x                  |vx                   ",
   "                             x     x x     x         px!!!!!!!!!!!!!!x                                        ",
   "                             x             x     x x xx            v x                                        ",
   "                             xx           xx                                                                  ",
   "  xxx                         x     x     x                                                              xxx  ",
   "  x x                         x    xxx    x                              *                               x x  ",
   "  x  o                        x    xxx    xxxx             yyy           x!xxx                             x  ",
   "  x                           x           x                              xv  x                             x  ",
   "  x  o                    yy  xx          x                                                 yyy            x  ",
   "  x                                       x     yyy    |xxxx|          xxx                                 x  ",
   "  x                xxx             o o    x                              x  x      |xxx                    x  ",
   "  x               xxxx        xx   yyy    x                             xxx       x!!!x          x         x  ",
   "  x               oxxxx       x         * x                             x x        xvx          xx         x  ",
   "  x                xxxo       xx!!xxxx!!xxx  x oo x    x oo x    x oo  xx xx                     xx        x  ",
   "  x      @          x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x        kx  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  [
   "                                                                                                              ",
   "             xxx                                                                                              ",
   "                                                                                                              ",
   "                         xxx                                                             xxx                  ",
   "                                                                                            x                 ",
   "                                                                 xx                        *x                 ",
   "                                     xxx                                                   x                  ",
   "                                                                                        xx                    ",
   "                                                          xx                                                  ",
   "                          o                                                          x                        ",
   "             x|x                                                                                            x ",
   "       yyy               x|x         x|x                                                                    x ",
   "                                                     xxx          *       yy                                x ",
   "                                                                 ||             xx         xxxxx            x ",
   "  xxxxxxxxxxx       x=          x       =x                                                                  x ",
   "  x=        * o xxxxxxxxx o xxxxxxxxx o xx                       xx                                         x ",
   "  x             x       x   x       x   x                 ||                             yyy                x ",
   "  x  @=     x |     o   xx|xx   o   xx|xx                                          p                       kx ",
   "  xxxxxxx                                     xxxxx       xx            xxx        xx               xxxxxxxxx ",
   "        x=                  =           *    =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],
   ["                          ",
    " x   x        x   x       ",
    " xx xx        x   x       ",
    "  xxx         x   x x     ",
	"   x          x x x       ",
    "   x xxx x x  xxxxx x xxx ",
    "   x x x x x  xx xx x x x ",
    "   x xxx xxx  x   x x x x ",
	"                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
